# Pandas Assignment - employees.csv

**Name:** A M Armaan  
**Reg. No:** URK24CS1021

### 1. Read the CSV file into a DataFrame

In [1]:
import pandas as pd

df = pd.read_csv('employees.csv')
df

,Employee_ID,Name,Gender,Age,Genre,Annual_Income,Appraisal Marks,Overall Score
0,201,Aarav,Male,24.0,Male,32000.0,78.0,82.0
1,202,Diya,Female,27.0,Female,35000.0,91.0,88.0
2,203,Rohan,Male,NaN,Male,30000.0,NaN,75.0
3,204,Ananya,Female,29.0,Female,NaN,86.0,90.0
4,205,Karan,Male,31.0,Male,42000.0,65.0,NaN
5,206,Meera,Female,26.0,Female,38000.0,NaN,79.0
6,207,Vikram,Male,NaN,Male,40000.0,72.0,84.0
7,208,Sara,Female,30.0,Female,NaN,95.0,92.0
8,209,Arjun,Male,28.0,Male,36000.0,68.0,76.0
9,210,Nisha,Female,25.0,Female,34000.0,NaN,85.0

### 2. Statistical information of the Appraisal Marks column

In [2]:
df['Appraisal Marks'].describe()

count     7.000000
mean     79.285714
std      11.657820
min      65.000000
25%      70.000000
50%      78.000000
75%      88.500000
max      95.000000
Name: Appraisal Marks, dtype: float64

### 3. Data type of the Age column

In [3]:
df['Age'].dtype

dtype('float64')

### 4. First 4 rows of Employee_ID, Name and Age

In [4]:
df[['Employee_ID', 'Name', 'Age']].head(4)

   Employee_ID    Name   Age
0          201   Aarav  24.0
1          202    Diya  27.0
2          203   Rohan   NaN
3          204  Ananya  29.0

### 5. Number of null values in each column

In [5]:
df.isnull().sum()

Employee_ID        0
Name               0
Gender             0
Age                2
Genre              0
Annual_Income      2
Appraisal Marks    3
Overall Score      1
dtype: int64

### 6. Rows where Appraisal Marks is null

In [6]:
df[df['Appraisal Marks'].isnull()]

,Employee_ID,Name,Gender,Age,Genre,Annual_Income,Appraisal Marks,Overall Score
2,203,Rohan,Male,NaN,Male,30000.0,NaN,75.0
5,206,Meera,Female,26.0,Female,38000.0,NaN,79.0
9,210,Nisha,Female,25.0,Female,34000.0,NaN,85.0

### 7. Fill null values with the previous value of the same column

In [7]:
df = df.ffill()
df

,Employee_ID,Name,Gender,Age,Genre,Annual_Income,Appraisal Marks,Overall Score
0,201,Aarav,Male,24.0,Male,32000.0,78.0,82.0
1,202,Diya,Female,27.0,Female,35000.0,91.0,88.0
2,203,Rohan,Male,27.0,Male,30000.0,91.0,75.0
3,204,Ananya,Female,29.0,Female,30000.0,86.0,90.0
4,205,Karan,Male,31.0,Male,42000.0,65.0,90.0
5,206,Meera,Female,26.0,Female,38000.0,65.0,79.0
6,207,Vikram,Male,26.0,Male,40000.0,72.0,84.0
7,208,Sara,Female,30.0,Female,40000.0,95.0,92.0
8,209,Arjun,Male,28.0,Male,36000.0,68.0,76.0
9,210,Nisha,Female,25.0,Female,34000.0,68.0,85.0

### 8. Fill the remaining null values with 0

After the forward fill no nulls are left, so this acts as a safety net for any value the previous step could not carry forward (e.g. a null in the very first row).

In [8]:
df = df.fillna(0)
df

,Employee_ID,Name,Gender,Age,Genre,Annual_Income,Appraisal Marks,Overall Score
0,201,Aarav,Male,24.0,Male,32000.0,78.0,82.0
1,202,Diya,Female,27.0,Female,35000.0,91.0,88.0
2,203,Rohan,Male,27.0,Male,30000.0,91.0,75.0
3,204,Ananya,Female,29.0,Female,30000.0,86.0,90.0
4,205,Karan,Male,31.0,Male,42000.0,65.0,90.0
5,206,Meera,Female,26.0,Female,38000.0,65.0,79.0
6,207,Vikram,Male,26.0,Male,40000.0,72.0,84.0
7,208,Sara,Female,30.0,Female,40000.0,95.0,92.0
8,209,Arjun,Male,28.0,Male,36000.0,68.0,76.0
9,210,Nisha,Female,25.0,Female,34000.0,68.0,85.0

### 9. Group the dataset based on Genre

In [9]:
grouped = df.groupby('Genre')

print(grouped.size())

grouped.mean(numeric_only=True)

Genre
Female    5
Male      5
dtype: int64

        Employee_ID   Age  Annual_Income  Appraisal Marks  Overall Score
Genre
Female        206.0  27.4        35400.0             81.0           86.8
Male          205.0  27.2        36000.0             74.8           81.4

### 10. Rows where Age > 25 and Genre is 'Female'

In [10]:
df[(df['Age'] > 25) & (df['Genre'] == 'Female')]

,Employee_ID,Name,Gender,Age,Genre,Annual_Income,Appraisal Marks,Overall Score
1,202,Diya,Female,27.0,Female,35000.0,91.0,88.0
3,204,Ananya,Female,29.0,Female,30000.0,86.0,90.0
5,206,Meera,Female,26.0,Female,38000.0,65.0,79.0
7,208,Sara,Female,30.0,Female,40000.0,95.0,92.0

### 11. Drop the Gender column permanently

In [11]:
df.drop('Gender', axis=1, inplace=True)
df

,Employee_ID,Name,Age,Genre,Annual_Income,Appraisal Marks,Overall Score
0,201,Aarav,24.0,Male,32000.0,78.0,82.0
1,202,Diya,27.0,Female,35000.0,91.0,88.0
2,203,Rohan,27.0,Male,30000.0,91.0,75.0
3,204,Ananya,29.0,Female,30000.0,86.0,90.0
4,205,Karan,31.0,Male,42000.0,65.0,90.0
5,206,Meera,26.0,Female,38000.0,65.0,79.0
6,207,Vikram,26.0,Male,40000.0,72.0,84.0
7,208,Sara,30.0,Female,40000.0,95.0,92.0
8,209,Arjun,28.0,Male,36000.0,68.0,76.0
9,210,Nisha,25.0,Female,34000.0,68.0,85.0

### 12. Sort the dataset based on Appraisal Marks in ascending order

In [12]:
df.sort_values('Appraisal Marks')

,Employee_ID,Name,Age,Genre,Annual_Income,Appraisal Marks,Overall Score
5,206,Meera,26.0,Female,38000.0,65.0,79.0
4,205,Karan,31.0,Male,42000.0,65.0,90.0
9,210,Nisha,25.0,Female,34000.0,68.0,85.0
8,209,Arjun,28.0,Male,36000.0,68.0,76.0
6,207,Vikram,26.0,Male,40000.0,72.0,84.0
0,201,Aarav,24.0,Male,32000.0,78.0,82.0
3,204,Ananya,29.0,Female,30000.0,86.0,90.0
1,202,Diya,27.0,Female,35000.0,91.0,88.0
2,203,Rohan,27.0,Male,30000.0,91.0,75.0
7,208,Sara,30.0,Female,40000.0,95.0,92.0

### 13. Drop the Overall Score column permanently

In [13]:
df.drop('Overall Score', axis=1, inplace=True)
df

   Employee_ID    Name   Age   Genre  Annual_Income  Appraisal Marks
0          201   Aarav  24.0    Male        32000.0             78.0
1          202    Diya  27.0  Female        35000.0             91.0
2          203   Rohan  27.0    Male        30000.0             91.0
3          204  Ananya  29.0  Female        30000.0             86.0
4          205   Karan  31.0    Male        42000.0             65.0
5          206   Meera  26.0  Female        38000.0             65.0
6          207  Vikram  26.0    Male        40000.0             72.0
7          208    Sara  30.0  Female        40000.0             95.0
8          209   Arjun  28.0    Male        36000.0             68.0
9          210   Nisha  25.0  Female        34000.0             68.0